name: Build
on:
  workflow_dispatch:
    inputs:
      nocache:
        type: boolean
        default: false

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sh -vx
          conda run bash -c 'ulimit -v'
          conda run bash -c 'ulimit -v unlimited'

