name: Build
on:
  workflow_dispatch:
    inputs:
      cache:
        type: boolean
        default: true

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.cache == true }}

