name: Build
on: 
  workflow_dispatch:
    inputs:
      nocache:
        type: boolean
        default: false
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      ASAN_OPTIONS: detect_leaks=0 verbosity=1
    steps:
      - uses: actions/checkout@v3
      - run: |
          sh -vx
          g++ test.cpp -o test -fsanitize=address
          ./test
