name: Benchmarking
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  push:

jobs:
  modin-containerized:
    uses: ./.github/workflows/test-docker.yml
    with:
      reset-cache: ${{ !!inputs.reset-cache }}

