name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV

  push: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          conda info
          conda update mamba
          mamba info
          mamba list

