name: Build
on: 
  workflow_dispatch:
    inputs:
      nocache:
        type: boolean
        default: false
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -vx
          date

#      - name: Build image
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: Dockerfile
#          push: false
#
#      - run: |
#          which libparquet.so.1100
