name: Build
on:
  workflow_dispatch:
    inputs:
      nocache:
        type: boolean
        default: false

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sh -vx
          ulimit -v
          cat /etc/security/limits.conf
          sudo bash -c 'ulimit -v 16000000000'
          cat /proc/meminfo
          ulimit -v unlimited

