name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV

  push: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo $CONDA/bin/conda
          ls -l /usr/bin/conda
          conda info
          $CONDA/bin/conda info

