name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV

  push: []

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo test >test.txt

      - name: Upload build and src files
        uses: actions/upload-artifact@v2
        with:
          name: test3
          path: test.txt


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Conda env if the cache is not updated
        uses: leshikus/action-download-artifact@master
        with:
          workflow: main.yml
          branch: ${{ github.ref_name }}
          workflow_conclusion:
          name: test3
          search_artifacts: true

