name: Build
on: 
  workflow_dispatch:
    inputs:
      nocache:
        type: boolean
        default: false
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      ASAN_OPTIONS: detect_leaks=0 verbosity=1
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -vx
          wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | \
            sudo gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg
          cat /usr/share/keyrings/intel-graphics.gpg
          sudo apt-add-repository \
            'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu '$(lsb_release -cs)' main'
          sudo apt-get update
          sudo apt-get install -y \
            intel-igc-cm \
            intel-level-zero-gpu \
            intel-media-va-driver-non-free \
            intel-opencl-icd \
            level-zero \
            level-zero-dev \
            libigc-dev \
            libigdfcl-dev \
            libigfxcmrt-dev \
            libmfx1          
