name: Build
on: 
  workflow_dispatch:
    inputs:
      nocache:
        type: boolean
        default: false
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -vx
          date
